project:
  type: website

website:
  navbar:
    background: primary
    search: true
    logo: Assets/CCWJ_white_logo.png
    logo-alt: Canada Centre for Welding and Joining

    left:
      - text: Home
        file: home/home.qmd

      - text: About us
        file: about/about.qmd

      - text: People
        file: people/director.qmd

      - text: Research
        file: research/research.qmd

      - text: Teaching
        file: teaching/teaching.qmd

      - text: Resources
        file: resources/resources.qmd

      - text: Join us
        file: join/joinus.qmd

    tools:
      - icon: twitter
        href: https://twitter.com/search?q=centre%20for%20welding%20and%20joining&src=typed_query&f=top
      - icon: linkedin
        href: https://www.linkedin.com/company/ccwj/
      - icon: github
        menu:
          - text: GitHub projects
            url:  https://github.com/ccwj-ualberta

  sidebar:
    - title: "Home"
      style: "docked"
      contents:
        - home/home.qmd
        - home/news.qmd

    - title: "About us"
      style: "docked"
      contents:
        - about/about.qmd
        - about/what-we-do.qmd
        - about/lab.qmd
        - about/welco-chair.qmd
        - about/advisory-boards.qmd
        - about/sponsors.qmd
        - about/directions.qmd
  
    - title: "People"
      style: "docked"
      contents:
        - people/director.qmd
        - people/staff.qmd
        - people/phds.qmd
        - people/mscs.qmd
        - people/bscs.qmd
        - people/alumn.qmd
        - people/alumn-ug.qmd
        - people/alumn-visitors.qmd
        
    - title: "Research"
      style: "docked"
      contents:
        - research/research.qmd
        - research/projects.qmd
        - research/publications.qmd
        - research/posters.qmd
      
    - title: "Teaching"
      style: "docked"
      contents:
        - teaching/teaching.qmd
        - teaching/welding.qmd
        - teaching/heat-transfer.qmd
    
    - title: "Resources"
      style: "docked"
      contents:
        - resources/resources.qmd
        - resources/videos.qmd
        - resources/gallery.qmd
        - resources/talks.qmd
    
    - title: "Join Us"
      style: "docked"
      contents:
        - join/joinus.qmd
        - join/canadian.qmd
        - join/international.qmd
        - join/visiting.qmd
        - join/upcoming-events.qmd
  
  page-footer:
    left: |
      Contact Information <br>
      Professor Patricio Mendez <br>
      ccwj@ualberta.ca
    center: |
      Shipping Address <br>
      Room CME L1-108 <br>
      University of Alberta <br>
      116 Street NW - 85 Avenue <br>
      Edmonton, AB T6G 2R3 Canada
    right: |
      Links <br>
      [Department of Chemical and Materials Engineering](https://www.ualberta.ca/engineering/chemical-materials-engineering/about-us/index.html) <br>
      [Directions](https://sites.ualberta.ca/~ccwj/About/directions.html) <br>
      [University of Alberta](https://www.ualberta.ca/)

format:
  html:
    # theme: cosmo
    css: styles.css
    toc: true
