project:
  type: website

  pre-render:
    - publications/create-articles.R
    - publications/create-proceedings.R
    - publications/create-reports.R

website:
  title: CCWJ
  favicon: assets/CCWJ_white_logo.png
  twitter-card: true
  open-graph: true

  navbar:
    title: false
    background: primary
    search: true
    logo: assets/CCWJ_white_logo.png
    logo-alt: Canada Centre for Welding and Joining

    left:
      - text: About
        file: about/about.qmd

      - text: People
        file: people/director.qmd

      - text: Research
        file: research/research.qmd

      - text: Publications
        file: publications/publications-articles.qmd

      - text: Teaching
        file: teaching/teaching.qmd

      - text: News
        file: news/news.qmd

      - text: Join Us
        file: apply/canadian.qmd

    tools:
      - icon: twitter
        href: https://twitter.com/search?q=centre%20for%20welding%20and%20joining&src=typed_query&f=top
      - icon: linkedin
        href: https://www.linkedin.com/company/ccwj/

  sidebar:
    - title: "About"
      style: "docked"
      contents:
      - section: "About Us"
        contents:
        - about/about.qmd
        - about/what-we-do.qmd
        - about/lab.qmd
        - about/welco-chair.qmd
        - about/directions.qmd
      - section: "Advisory Boards and Sponsors"
        contents:
        - about/advisory-boards.qmd
        - about/sponsors.qmd

    - title: "People"
      style: "docked"
      contents:
        - people/director.qmd
        - people/staff.qmd
        - people/phds.qmd
        - people/mscs.qmd
        - people/bscs.qmd
        - people/alumn.qmd
        - people/alumn-ug.qmd
        - people/alumn-visitors.qmd

    - title: "Research"
      style: "docked"
      contents:
        - research/research.qmd
        - research/projects.qmd
        - research/talks.qmd
        - research/posters.qmd
        - research/videos.qmd

    - title: "Teaching"
      style: "docked"
      contents:
        - teaching/teaching.qmd

    - title: "Publications"
      style: "docked"
      contents:
        - publications/publications-articles.qmd
        - publications/publications-books.qmd
        - publications/publications-proceedings.qmd
        - publications/publications-reports.qmd
        - publications/publications-theses.qmd

    - title: "Join Us"
      style: "docked"
      contents:
        - section: "Canadian"
          contents:
          - apply/canadian.qmd

        - section: "International"
          contents:
            - section: "Graduate Studies"
              contents:
                - apply/international-graduate.qmd
                - apply/international-resources-for-visiting.qmd
            - apply/international-undergrad.qmd

  page-footer:
    left: |
      Contact Information <br>
      [Professor Patricio Mendez](mailto:ccwj@ualberta.ca) <br>
    center: |
      Room CME L1-108 <br>
      University of Alberta <br>
      116 Street NW - 85 Avenue <br>
      Edmonton, AB T6G 2R3 Canada
    right: |
      [Department of Chemical and Materials Engineering](https://www.ualberta.ca/engineering/chemical-materials-engineering/about-us/index.html) <br>
      [Directions](https://sites.ualberta.ca/~ccwj/About/directions.html) <br>
      [University of Alberta](https://www.ualberta.ca/)

format:
  html:
    toc: false

theme: custom.scss
