---
title: "Canadian Students"
toc: true
---

## If you would like to work at the CCWJ

### Graduate Studies

#### General Information

The following link contains general information by the Faculty of Engineering about the application process for graduate studies.

https://www.ualberta.ca/engineering/chemical-materials-engineering/graduate-studies/index.html

### Undergraduate Studies

#### General Information

The following link contains general information by the Faculty of Engineering about the application process for undergraduate studies.

https://www.ualberta.ca/engineering/chemical-materials-engineering/undergraduate-programs.html

### High-School Students

#### Alberta Innovates Alberta Innovates Summer Studentships

https://www.ualberta.ca/current-students/undergraduate-research-initiative/navigating-research-process/funding/alberta-innovates-summer-studentships.html

## If you would like to travel and visit some of our academic partners

### RWTH Aachen Undergraduate Research Opportunities Program (UROP)

https://www.ualberta.ca/international/go-abroad/programs/rwth-aachen-university-undergraduate-research-opportunities-program-urop-internship.html

### RWTH Junior Research Fellowship (Master's/PhD)

https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/rwth-aachen-junior-research-fellowships/index.html

### RWTH Aachen - Exchange

https://www.ualberta.ca/international/go-abroad/programs/rwth-aachen-university-exchange.html

### Hiroshima

Please contact us directly for more details.

### UofA Go Abroad Programs

Here you will find an overview of internships internships/exchanges available through the University of Alberta

https://www.ualberta.ca/international/go-abroad/programs/index.html
