---
title: "Resources for Visiting Students"
toc: true
---

## Prior to your visit

### Finding Accommodations

If you are looking for an accommodation for your internship or studies with us, the link above includes some resources compiled by University of Alberta International that might be of help to you.

https://www.ualberta.ca/international/international-student-services/prepare-for-ualberta/find-housing.html

### University of Alberta International

The International Office of the University of Alberta is the central connecting point for visiting and international students. Their website contains extremely useful information and resources for visiting students.

https://www.ualberta.ca/international/index.html

### Research Internships available at the University of Alberta

This link contains general information about research internships available at the University of Alberta.

https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/index.html

### Request a Letter of Invitation for International Scholarships Programs

https://docs.google.com/forms/d/e/1FAIpQLSdnuXjmbKJ3WsKJLbEDW8y9QWIVFE8EBQRsCgKJw_5XLUcqQA/viewform

### Visiting Student and Internship Programs

https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/index.html

## After completing your visit

### Request a letter of recommendation

Recommendation Letter Request Form

https://docs.google.com/forms/d/e/1FAIpQLSfUAAMAFBlM-yvo5HaoKy0DKcMKinhDq8sbYmL2Bf_5pwN6FQ/viewform
