---
title: Sandeep Singh  Sulinderpal Singh Parmar Sandeep Singh
subtitle: Materials Engineering
about:
  template: solana
  links:
    - icon: email
      text: sandeeps@ualberta.ca
      href: sandeeps@ualberta.ca
---

First Joined CCWJ: Sep 28, 2022
Country of Origin: India
My Dreams: Welding Engineer with P Eng designation preferably in Nuclear, Aerospace or defense industry here in Canada.
Hobbies: Playing Cricket, Cycling, Adventure Sports, watching investigation shows (Air Crash, Criminal cases etc.)
Awards: 
1. Led the team SFT (for implementation and successful execution of six sigma project) at Hendrickson Commercial Vehicle Systems (American Company) who won the 1st prize in overall category (Productivity, Quality, and Cost) at 14th Quality Circle Competition in the year 2019.
2. Bronze Award for development and deployment of fixture for Procedure and Performance Qualification at General Electric in the year 2018.
3.Silver Award for Increase of the weld deposition rate at General Electric in the year 2017.
4. Based on my story (relating to the training I have undergone as a Trainee) my Mentor whose was also my Manager at Essar Heavy Engineering Services was awarded with Star Fish award by Chairman of ESSAR in the year 2009.
5. 2nd Rank (Equivalent to a silver medal-well from 3rd year onwards university started giving money instead of medals) in 3rd year during my undergraduate study at Ganpat University in the year 2007.
6. Best Fielder Award in District level cricket tournament held in the year 1998.

## Project

I have approximately 14 years of experience working as a Welding Engineer and QC Engineer for manufacturing of equipment's for Oil and Energy (Thermal, Hydro, and Wind), Petrochemical, Fertilizer, Railways, and automotive sectors, and have WPS, PQR and WPQ/WOPQ qualification related know how of metallurgies such as C-Mn steel, low alloy steel, stainless steel, high strength steel, copper alloys, nickel alloys and titanium alloy. 
I did my international welding engineer Diploma (completed in year 2018) with Project titled: "Procedure Qualification for Aluminum Bronze Weld Overlay on unalloyed fine-grained C-Mn steel as per BS EN ISO 15614-7" - application mainly seal carrier ring of MIV valve meant for hydro power plant. 
I also did my Associate degree in Welding Technology from Indian Institute of Welding (in the Year 2019) with Project titled: "Monel 400 Weld Overlay (ENiCu-7) on SA 516 Gr 70 (Base Material) to achieve undiluted chemistry at 3 mm height from the base material surface as per ASME SEC IX using SMAW process (half bead technique)."-application channel side weld overlay and clad restoration in heat exchanger meant for sea water service.