---
title: "Heat Transfer"
description: "This is an engineering course in which we aim at introducing students to the fundamental aspects of welding engineering in the best possible way: in front of the actual equipment. After completing this course students should master the concepts related to a vast variety of welding processes, the laws of nature on which they operate, related materials issues, and the practical implications of the new concepts learned, including the writing of a welding procedure."
author: "Professor Patricio Mendez"
date: "2021-09-01"
format:
  html:
    toc: true
    link-external-icon: true
    link-external-new-tab: true
---

CH E 314 - Heat Transfer

Heat Transfer is at the core of welding. This course includes the fundamental principles that can be used to scientifically understand the welding processes, including the principles of conduction, convection and radiation heat transfer. The course includes design and performance analysis of thermal systems based on these principles, which apply to a wide range of engineering applications and disciplines.

[Syllabus 2021](https://drive.google.com/file/d/1kMOk89UhfOb8htVnvp8h_7zg6wVONGaM/view?usp=sharing)

### 2021 Lectures

{{< video https://youtu.be/hqXmFBIFtAI?list=PLq-4Q87XIqZExUyjrnVcCjQF2GyRtmPcB >}}

#### Energy balances

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/1_Energy_balances/Handout/LaTex/energy_balances.pdf)

#### Heat transfer mechanisms

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/2_Heat_transfer_mechanisms/Handout/LaTex/heat_transfer_mechanisms.pdf)

#### Lumped capacitance

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/3_Lumped_capacitance/Handout/LaTex/lumped_capacitance.pdf)

#### Differential control volumes

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/4_Differential_control_volumes/Handout/LaTex/differential_control_volumes.pdf)

#### 1D Conduction steady-state-Thermal resistance

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/5_1D_Conduction_steady-state-Thermal_resistance/Handout/LaTex/steady-state_conduction_1D_thermal_resistance.pdf)

#### Steady-state conduction beyond 1D

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/6_Steady-state_conduction_beyond_1D/Handout/LaTex/steady_state_conduction_beyond_1D.pdf)

#### Transient conduction-Semi-infinite solid

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/7_Transient_conduction-Semi-infinite_solid/Handout/LaTex/transient_conduction_semi-infinite_solid.pdf)

#### External flows-Boundary Layer

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/8_External_flows-Boundary_Layer/Handout/LaTex/boundary_layers-external_flows.pdf)

#### Internal flows

[Slides](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/9_Internal_flows/Slides/internal_flows_slides.pdf)

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/9_Internal_flows/Handout/LaTex/internal_flows.pdf)

#### Natural convection

[Slides](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/10_Natural_convection/Slides/natural_convection_slides.pdf)

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/10_Natural_convection/Handout/LaTex/natural_convection.pdf)

#### Boiling and condensation

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/11_Boiling_and_condensation/Handout/LaTex/boiling_and_condensation.pdf)

#### Heat exchangers

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/12_Heat_exchangers/Handout/LaTex/heat_exchangers.pdf)

#### Radiation

[view factors cylinders](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/13_Radiation/Supplemental_Material/view_factors_cylinders.pdf)

[example13.3](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/13_Radiation/Supplemental_Material/example13.3.pdf)

[general view factors.](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/13_Radiation/Supplemental_Material/general_view_factors.pdf)

[Handout](https://sites.ualberta.ca/~ccwj/Assets/Teaching/CHE314/13_Radiation/Handout/LaTex/radiation.pdf)
