---
title: "Our Impact"
engine: knitr
---

```{r setup}
#| message: false
#| warning: false
#| echo: false
library(scholar)
library(dplyr)
library(ggplot2)

scholar_id = get_scholar_id("Mendez", "Patricio", affiliation = "University of Alberta")
scholar_pfl = get_profile(scholar_id)
pubs = as_tibble(get_publications(scholar_id))
ct = get_citation_history(scholar_id)
```

```{r}
#| layout-ncol: 2
#| message: false
#| warning: false
#| echo: false
pubs |>
    filter(year >= 2006) |>
    group_by(year) |> 
    tally() |> 
    mutate(n = cumsum(n)) |> 
    ggplot(aes(year, n)) +
    geom_col(fill = "#466B46") +
    theme_minimal() +
    theme(axis.title = element_blank()) +
    ggtitle("CCWJ Yearly Publications")

pubs |>
    filter(year >= 2006) |>
    ggplot(aes(year)) +
    geom_bar(fill = "#466B46") +
    theme_minimal() +
    theme(axis.title = element_blank()) +
    ggtitle("CCWJ Yearly Publications")

ct |>
    filter(year >= 2006) |>
    ggplot(aes(year, cites)) +
    geom_point() +
    geom_line() +
    theme_minimal()
```

```{r}
#| message: false
#| warning: false
#| echo: false
#| layout-ncol: 2
library(here)
library(glue)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(lubridate)

grants = read_csv(here("about/CCWJ-research-grants.csv"))

grants = grants |>
    mutate(across(c(Start, End), as.Date)) |>
    drop_na(Start)

total_m = sum(grants$Total)
total_m = round(total_m / 1000000, 1)

grants |>
    group_by(Year = year(Start)) |>
    summarize(Total = sum(Total), .groups = "drop") |>
    mutate(Total = cumsum(Total)) |>
    ggplot(aes(Year, Total)) +
    geom_col(fill = "#466B46") +
    scale_y_continuous(labels = scales::dollar_format()) +
    ggtitle(
        "Research Grants and Contracts",
        glue("Cumulative Total Funding of ${total_m}M since 2009")
    ) +
    theme_minimal() +
    theme(axis.title.y = element_blank())
```

```{r}
equipment = read_csv(here("about/CCWJ-equipment-grants.csv"))

equipment = equipment |>
    mutate(across(c(Start, End), as.Date))

total_m = sum(equipment$Total)
total_m = round(total_m / 1000000, 1)
```

