---
title: "Undergraduate Studies"
---

### Scholarships and Exchange Programs

- [France International Mobility Program](https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/francophone-mobility.html)

- [ELAP](https://www.scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng)
  - Undergraduate and graduate students from the Caribbean and South America

- [Canada-ASEAN Scholarships and Educational Exchanges for Development (SEED)](https://scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/asean-anase.aspx?lang=eng
)
  - Undergraduate and graduate students from ASEAN member states

- [China Scholarship Council (CSC) Funded Internships](https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/csc-funded-placements/index.html)
  - The China Scholarship Council provides funding to undergraduate students
from Double First-Class Initiative universities in China to conduct
research ­at UAlberta under the supervision of faculty members who are
experts in their field.

- [Study in Canada Scholarships](https://www.educanada.ca/scholarships-bourses/can/institutions/study-in-canada-sep-etudes-au-canada-pct.aspx?lang=eng)
  - Undergraduate and graduate students from: Asia: Bangladesh, Nepal,
Taiwan; Europe: Turkey, Ukraine; The Middle East and North Africa:
Algeria, Egypt, Jordan, Libya, Morocco, Tunisia; Sub-Saharan Africa:
Burkina Faso, Ethiopia, Ghana, Ivory Coast, Kenya, Nigeria, Rwanda,
Senegal, Tanzania, Uganda

- [UARE](https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/ualberta-research-experience/index.html)
  - The UARE provides a unique opportunity for talented senior undergraduate
students from key partner universities around the world to conduct
research under the supervision of faculty members who are experts in
their field.

- [Mitacs Globalink](https://www.mitacs.ca/en/programs/globalink)
  - Take your research abroad with Mitacs Globalink. Globalink offers travel
funding between Canada and several international partners.

- [Request a Letter of Invitation for International Scholarships Programs](https://docs.google.com/forms/d/e/1FAIpQLSdnuXjmbKJ3WsKJLbEDW8y9QWIVFE8EBQRsCgKJw_5XLUcqQA/viewform)
